### PR TITLE
add docker image generation

### PR DESCRIPTION
**Pull request by andreaturli**

### CODE REVIEW

**Comment by tbouron** [comment]
Thanks @andreaturli for this, it's great!
However, I get an error when I try to build it:
```
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.0:build (default) on project brooklyn-dist: Could not build image: com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.spotify.docker.client.messages.RegistryAuth` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('swarm')
[ERROR]  at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: java.util.LinkedHashMap["stackOrchestrator"])
[ERROR] -> [Help 1]
```
Does this require some setup to do first? If yes, I would suggest to add a flag to disable the docker build, same as `-D no-deb` or `-D no-rpm`

**Comment by tbouron** [comment]
Tested this again and it works like a charm. The plugin (https://github.com/spotify/docker-maven-plugin) come with all the flag necessary to disable the build and push directly the image we just build if if needed.

This looks very promising, thanks @andreaturli 👍

**Comment by geomacy** [comment]
hi @tbouron what did you do exactly to get round the build error above?

I'm getting
```
[ERROR] Failed to execute goal com.spotify:dockerfile-maven-plugin:1.4.0:build (default) on project brooklyn-dist: Could not build image: com.spotify.docker.client.shaded.com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.spotify.docker.client.messages.RegistryAuth` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('osxkeychain')
[ERROR]  at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: java.util.LinkedHashMap["credSstore"])
```

**Comment by geomacy** [comment]
Upgrading the dockerfile-maven-plugin to 1.4.3 fixed the above for me - have raised https://github.com/apache/brooklyn-dist/pull/130

**Comment by tbouron** [comment]
Hi @geomacy. Indeed, the plugin updated to the latest version when I retested it which worked. Should we bump the version?

**Comment by tbouron** [comment]
Aaaah just saw your PR @geomacy, never mind then :)

**Comment by Vilseifittan** [comment]
hey when i was registration my dumbfuccked ass full of subSctances exit me i put my old friking mail in thats not working🤮 please help me guys

**Pull request merged**
