### PR TITLE
lower minimum Vagrant version to 1.8.0

### PR DESCRIPTION
**Pull request by johnmccabe**
- verified locally on OSX myself and via @neykov

### CODE REVIEW

**Comment by johnmccabe** [comment]
Following discussion on dev list [here](http://mail-archives.apache.org/mod_mbox/incubator-brooklyn-dev/201604.mbox/%3C9DB9EFC3-48FA-45BA-8CFC-C92D9242EE11%40cloudsoftcorp.com%3E)

**Comment by johnmccabe** [comment]
fyi @neykov @richardcloudsoft

**Comment by neykov** [comment]
Tested with vagrant `1.7.0`. It's failing with `The following settings shouldn't exist: env`. Seems this was introduced in 1.8.0. So either need to move away from using env or bump the version to `1.8.0`.

**Comment by johnmccabe** [comment]
@neykov thats very odd, I ran with 1.7.0 locally  (wiped Vagrant and installed the old version)...

Are you running on OSX/Windows or Linux?

**Comment by johnmccabe** [comment]
Hmm, looks like my 1.8.1 hadn't been blown away, was in `/usr/local/bin/vagrant` rather than the `/usr/bin/vagrant` that the Vagrant docs on uninstallation refer to..

Regarding getting rid of env, I'd don't think we should do that to cater to users running obsolete versions

**Comment by neykov** [comment]
I tested on Ubuntu 14.04. Btw by default it install `1.4.3` :).

**Comment by johnmccabe** [comment]
We'd only been targeting OSX and Windows

**Comment by neykov** [comment]
Getting the following error when testing with `1.8.0`
```
==> brooklyn: Destroying VM and associated drives...
/opt/vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/provisioners/shell/provisioner.rb:162:in `quote_and_escape': undefined method `gsub' for false:FalseClass (NoMethodError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/provisioners/shell/provisioner.rb:50:in `block in provision_ssh'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/provisioners/shell/provisioner.rb:50:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/provisioners/shell/provisioner.rb:50:in `map'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/provisioners/shell/provisioner.rb:50:in `provision_ssh'
```

Related to https://github.com/mitchellh/vagrant/issues/6707. Needed to convert the `false` in the env section to a string by quoting it.

Also updating the packages takes forever, adding the following to `Vagrantfile` speeds it up considerably.
```
	vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
	vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
```

Still waiting for the `up` to complete, will report with the result.

**Comment by johnmccabe** [comment]
@neykov Ubuntu 14.04 again?

Interesting tweak to the nics!!

**Comment by neykov** [comment]
Testing on OS X now. Turns out that virtualbox can't run inside another VM. Other than that the host shouldn't make a difference.

Removing the failing `vagrant-catalog.bom` allowed me to start brooklyn. It's listening on `127.0.0.1:8081` only. Can't connect to it on the `10.10.10.x` network. The port is not mapped on the NAT interface as well (no `forwarded_ports` section inside the yaml).

**Comment by neykov** [comment]
Fixed the binding problem in https://github.com/apache/brooklyn-server/pull/101, affects only master branch (0.10.x versions)

**Comment by johnmccabe** [comment]
@neykov is there anything else I need to do before we merge this?

**Comment by neykov** [comment]
`1.8.0` won't work unless all env keys & values are strings, see this comment https://github.com/apache/brooklyn-dist/pull/30#issuecomment-205778386

**Comment by johnmccabe** [comment]
Ah ok, missed that, I'll ping you when I submit a fix.

**Comment by johnmccabe** [comment]
Feels like a bad move to hack around a fixed bug in `1.8.0` that has been addressed in `1.8.1` - tempted to close the PR and leave as-is here but add a comment to the getting started steps. wdyt?

**Comment by neykov** [comment]
Works for me.

**Comment by johnmccabe** [comment]
Closing

**Pull request closed without merging**
