### PR TITLE
Updates due to karaf update to 4.1.2

### PR DESCRIPTION
**Pull request by m4rkmckenna**
(see https://github.com/apache/brooklyn-server/pull/771)

### CODE REVIEW

**Comment by neykov** [comment]
If we are changing logging providers, perhaps it's the right time to look at using logback, as was the initial plan?
Any preferences here for log4j2 vs logback?

**Comment by m4rkmckenna** [comment]
I have a preference for log4j2 as I know it better and I have a plan to use the JSON Layout for something

Do you think logback is better?

**Comment by tbouron** [comment]
+1 on log4j2, but it's personal preference

**Comment by geomacy** [comment]
I'm getting jclouds wire logging appearing in the default log file with this config

**Comment by geomacy** [comment]
it's quite verbose output especially with the fixed width formats eg.
```
2017-07-21T11:34:20,918 | DEBUG | qtp43713279-146  | BrooklynEntityMatcher            | 121 - org.apache.brooklyn.camp - 0.12.0.SNAPSHOT | Item Service[name=<null>,description=<null>,serviceType=org.apache.brooklyn.entity.messaging.qpid.QpidQueue,characteristics=[],customAttributes={}] being instantiated with org.apache.brooklyn.entity.messaging.qpid.QpidQueue
```
versus
```
2017-07-20 16:03:01,909 DEBUG 120 o.a.b.c.b.s.c.BrooklynEntityMatcher [nager-SFHUWtaA-0] Item Service[name=<null>,description=<null>,serviceType=org.apache.brooklyn.entity.messaging.qpid.QpidQueue,characteristics=[],customAttributes={}] being instantiated with org.apache.brooklyn.entity.messaging.qpid.QpidQueue
```

**Comment by m4rkmckenna** [comment]
@geomacy Ive amended the log format (back to old format) and ive set `jclouds.wire` to `OFF`

Both fixed in 50d3470

**Pull request merged**
